# Generated by Django 3.0.5 on 2020-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlocation',
            name='stud_pnumber',
            field=models.CharField(max_length=50),
        ),
    ]
